## Obtaining the Efficient Frontier - Part II

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

Ok, let’s continue the exercise from the last lecture.

You already downloaded the data and generated two random weightings. 

In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt
%matplotlib inline

assets = ['WMT', 'FB']
pf_data = pd.read_csv(r'C:\Users\Admin\OneDrive\Documents\bt ptdl\bt_tuan_ptdl\DA07 - Phan tich du lieu tai chinh\04_normative_finance\04_normative_finance\01_Obtaining the Efficient Frontier_1\csv\Walmart_FB_2014_2017.csv', index_col='Date')

In [2]:
log_returns = np.log(pf_data / pf_data.shift(1))

num_assets = len(assets)

weights = np.random.random(num_assets)
weights /= np.sum(weights)
weights

array([0.345187, 0.654813])

Now, estimate the expected Portfolio Return, Variance, and Volatility.

Expected Portfolio Return:

In [3]:
np.sum(weights * log_returns.mean()) * 250

np.float64(0.1894445346652116)

Expected Portfolio Variance:

In [4]:
np.dot(weights.T, np.dot(log_returns.cov() * 250, weights))

np.float64(0.04322326722691695)

In [5]:
log_returns.cov()

,WMT,FB
WMT,0.000126,0.000035
FB,0.000035,0.000331


In [6]:
weights

array([0.345187, 0.654813])

In [7]:
weights.T

array([0.345187, 0.654813])

In [8]:
a = np.dot(log_returns.cov() * 250, weights)
a

array([0.01663562, 0.05723904])

In [9]:
np.dot (weights, a)

np.float64(0.04322326722691695)

Expected Portfolio Volatility:

In [10]:
np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights)))

np.float64(0.20790206162257496)

***

The rest of this exercise will be a reproduction of what we did in the previous video.

1)	Create two empty lists. Name them pf_returns and pf_volatilites.

In [11]:
pfolio_returns = []
pfolio_volatilities = []

2)	Create a loop with 1,000 iterations that will generate random weights, summing to 1, and will append the obtained values for the portfolio returns and the portfolio volatilities to pf_returns and pf_volatilities, respectively.

In [12]:
for x in range (1000):
    weights = np.random.random(num_assets)
    weights /= np.sum(weights)
    pfolio_returns.append(np.sum(weights * log_returns.mean()) * 250)
    pfolio_volatilities.append(np.sqrt(np.dot(weights.T,np.dot(log_returns.cov() * 250, weights))))
    
pfolio_returns, pfolio_volatilities

([np.float64(0.194250882967643),
  np.float64(0.179939707757414),
  np.float64(0.015628327624830584),
  np.float64(0.12225121009038967),
  np.float64(0.20039253196066847),
  np.float64(0.13170705532980143),
  np.float64(0.14848887096385524),
  np.float64(0.08131941703091333),
  np.float64(0.17723338939434866),
  np.float64(0.11721275056044346),
  np.float64(0.08702832362066339),
  np.float64(0.11116564814057983),
  np.float64(0.16471756307280283),
  np.float64(0.14334544146083117),
  np.float64(0.10707944985333816),
  np.float64(0.15914038641099945),
  np.float64(0.19483726114447533),
  np.float64(0.15741381681428418),
  np.float64(0.26032444647680925),
  np.float64(0.12298704835164855),
  np.float64(0.03366502202908767),
  np.float64(0.1499985942673469),
  np.float64(0.16775751846253126),
  np.float64(0.23269095091491915),
  np.float64(0.09018887033875166),
  np.float64(0.16901006671565758),
  np.float64(0.13111451682674935),
  np.float64(0.049695376770439774),
  np.float64(0.10655488

3)	Transform the obtained lists into NumPy arrays and reassign them to pf_returns and pf_volatilites. Once you have done that, the two objects will be NumPy arrays. 

In [13]:
pfolio_returns = np.array(pfolio_returns)
pfolio_volatilities = np.array(pfolio_volatilities)

pfolio_returns, pfolio_volatilities

(array([0.19425088, 0.17993971, 0.01562833, 0.12225121, 0.20039253,
        0.13170706, 0.14848887, 0.08131942, 0.17723339, 0.11721275,
        0.08702832, 0.11116565, 0.16471756, 0.14334544, 0.10707945,
        0.15914039, 0.19483726, 0.15741382, 0.26032445, 0.12298705,
        0.03366502, 0.14999859, 0.16775752, 0.23269095, 0.09018887,
        0.16901007, 0.13111452, 0.04969538, 0.10655488, 0.13488467,
        0.05663863, 0.23855749, 0.11181843, 0.05876567, 0.25751511,
        0.04737106, 0.11579973, 0.15164486, 0.11924816, 0.14102079,
        0.18311958, 0.2841213 , 0.12173932, 0.28131998, 0.10938572,
        0.23308293, 0.25475106, 0.00666597, 0.25983257, 0.10062263,
        0.16561993, 0.17434195, 0.12948311, 0.08409907, 0.15127703,
        0.14211851, 0.08659014, 0.11278542, 0.07359085, 0.11152061,
        0.16202108, 0.01145115, 0.07677035, 0.14618278, 0.17915551,
        0.11508982, 0.20348041, 0.16953845, 0.12039116, 0.18682819,
        0.10260171, 0.26938876, 0.12142543, 0.16