In [1]:
# train a linear regrssion model using Pseudo inverse of A

import numpy as np

A = [[40, 30, 1],
     [30, 80, 1],
     [20, 70, 1],
     [70, 40, 1],
     [60, 20, 1]]

Z = [[1], [-1], [-1], [1], [1]]

In [2]:
At = np.transpose(A)

print(At)

[[40 30 20 70 60]
 [30 80 70 40 20]
 [ 1  1  1  1  1]]


In [3]:
AtA = np.dot(At,A)
AtZ = np.dot(At,Z)

print(AtA)
print(AtZ)

[[11400  9000   220]
 [ 9000 14200   240]
 [  220   240     5]]
[[120]
 [-60]
 [  1]]


In [4]:
inv_AtA = np.linalg.inv(AtA)
X = np.dot(inv_AtA,AtZ)

In [6]:
print(X)

[[ 0.01617647]
 [-0.03088235]
 [ 0.97058824]]


### Hồi quy tuyến tính

In [2]:
import numpy as np

# Dữ liệu
X = np.array([[40, 30, 1],
              [30, 80, 1],
              [20, 70, 1],
              [70, 40, 1],
              [60, 20, 1]])
Y = np.array([[1], [-1], [-1], [1], [1]])

# Tính theta bằng pseudo-inverse
Xt = X.T
theta = np.linalg.inv(Xt @ X) @ Xt @ Y

print("Weights (theta):\n", theta)

# Dự đoán
Y_pred = X @ theta
print("Predictions:\n", Y_pred)

# Residual error
residual = Y - Y_pred
print("Residual:\n", residual)


Weights (theta):
 [[ 0.01617647]
 [-0.03088235]
 [ 0.97058824]]
Predictions:
 [[ 0.69117647]
 [-1.01470588]
 [-0.86764706]
 [ 0.86764706]
 [ 1.32352941]]
Residual:
 [[ 0.30882353]
 [ 0.01470588]
 [-0.13235294]
 [ 0.13235294]
 [-0.32352941]]


### Hồi quy logistic

In [3]:
import numpy as np

# Dữ liệu (giả sử Y là 0 hoặc 1)
X = np.array([[40, 30, 1],
              [30, 80, 1],
              [20, 70, 1],
              [70, 40, 1],
              [60, 20, 1]])
Y = np.array([[1], [0], [0], [1], [1]])

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Khởi tạo weights
theta = np.zeros((X.shape[1],1))
alpha = 0.001
iterations = 10000

# Gradient descent
for i in range(iterations):
    z = X @ theta
    h = sigmoid(z)
    gradient = X.T @ (h - Y) / Y.size
    theta -= alpha * gradient

print("Weights (theta):\n", theta)

# Dự đoán xác suất
Y_prob = sigmoid(X @ theta)
print("Predicted probabilities:\n", Y_prob)

# Chuyển xác suất sang nhãn 0/1
Y_pred = (Y_prob >= 0.5).astype(int)
print("Predicted labels:\n", Y_pred)


Weights (theta):
 [[ 0.34190769]
 [-0.22506605]
 [ 0.00482401]]
Predicted probabilities:
 [[9.99022125e-01]
 [4.33480971e-04]
 [1.34791651e-04]
 [9.99999674e-01]
 [9.99999889e-01]]
Predicted labels:
 [[1]
 [0]
 [0]
 [1]
 [1]]
